
function openSettings(){openModal("Configurações",`<div class="form"><label>Tema<select id="themeSelect"><option value="system" ${data.settings.theme==="system"?"selected":""}>Sistema</option><option value="light" ${data.settings.theme==="light"?"selected":""}>Claro</option><option value="dark" ${data.settings.theme==="dark"?"selected":""}>Escuro</option></select></label><button class="btn primary" onclick="saveSettings()">Salvar aparência</button><hr><button class="btn" onclick="downloadBackup()">Exportar backup JSON</button><label>Importar backup JSON<input type="file" accept=".json" onchange="importBackup(event)"></label><small>O backup do Planner V8 está preservado no Git. Este backup contém apenas o Minha Vida V1.</small></div>`);}
function saveSettings(){data.settings.theme=document.getElementById("themeSelect").value;persist();closeModal();render();}
function downloadBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`minha-vida-v1-backup-${today()}.json`;a.click();URL.revokeObjectURL(u);toast("Backup gerado");}
function importBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const parsed=parseJSON(r.result,null);if(!parsed){alert("Arquivo inválido");return}data=normalize(parsed);persist();closeModal();render();toast("Backup importado")};r.readAsText(f);}

function readSession(){return parseJSON(localStorage.getItem(SESSION_KEY),null);}
function storeSession(s){currentSession=s||null;currentUser=s?.user||null;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY);}
async function api(path,{method="GET",body,auth=true,headers={}}={}){const h=Object.assign({apikey:SUPABASE_KEY},headers);if(body!==undefined)h["Content-Type"]="application/json";if(auth){const s=await ensureSession();if(!s?.access_token)throw new Error("Sessão expirada");h.Authorization=`Bearer ${s.access_token}`;}const res=await fetch(`${SUPABASE_URL}${path}`,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const raw=await res.text();const payload=parseJSON(raw,raw);if(!res.ok)throw new Error(payload?.msg||payload?.message||payload?.error_description||payload?.error||`Erro ${res.status}`);return payload;}
async function ensureSession(){let s=currentSession||readSession();if(!s)return null;if(s.expires_at&&s.expires_at>Date.now()/1000+60){storeSession(s);return s}if(!s.refresh_token){storeSession(null);return null}try{const r=await api("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:{refresh_token:s.refresh_token},auth:false});r.expires_at=r.expires_at||Math.floor(Date.now()/1000)+(r.expires_in||3600);storeSession(r);return r}catch{storeSession(null);return null}}
async function readCloudRow(){const rows=await api(`/rest/v1/planner_state?user_id=eq.${encodeURIComponent(currentUser.id)}&select=state,updated_at`);return Array.isArray(rows)?rows[0]||null:null;}
async function saveLifeToCloud(silent=false){if(!currentUser||!navigator.onLine)return false;try{const row=await readCloudRow();const state=row?.state&&typeof row.state==="object"?row.state:{};state.lifeV1=data;await api("/rest/v1/planner_state?on_conflict=user_id",{method:"POST",body:{user_id:currentUser.id,schema_version:CLOUD_SCHEMA,state,updated_at:nowISO()},headers:{Prefer:"resolution=merge-duplicates,return=minimal"}});setSync("online","Sincronizado");if(!silent)toast("Sincronizado");return true}catch(e){console.error(e);setSync("error","Falha na nuvem");if(!silent)toast("Dados locais preservados");return false}}
async function initCloud(){const s=await ensureSession();if(!s){updateAccountUI();return}storeSession(s);setSync("saving","Buscando dados…");try{const row=await readCloudRow();if(row?.state?.lifeV1){const cloud=normalize(row.state.lifeV1);if(String(cloud.updatedAt||"")>=String(data.updatedAt||"")){data=cloud;localStorage.setItem(LIFE_KEY,JSON.stringify(data));}else await saveLifeToCloud(true);}else await saveLifeToCloud(true);setSync("online","Sincronizado");}catch(e){console.error(e);setSync("error","Modo local");}render();}
function updateAccountUI(){const el=document.getElementById("accountEmail"),btn=document.getElementById("accountButton");if(el)el.textContent=currentUser?.email||"Dados locais";if(btn)btn.textContent=currentUser?"Conta":"Entrar";if(!currentUser)setSync("","Neste dispositivo");}
function openAccount(){if(currentUser){openModal("Conta",`<div class="form"><div class="auth-note"><b>${esc(currentUser.email||"")}</b><br>Os dados do Minha Vida são sincronizados na mesma conta do antigo Planner.</div><button class="btn primary" onclick="saveLifeToCloud()">Sincronizar agora</button><button class="btn" onclick="logout()">Sair</button></div>`);return}openModal("Entrar",`<div class="form"><label>E-mail<input id="authEmail" type="email" autocomplete="email"></label><label>Senha<input id="authPassword" type="password" minlength="6" autocomplete="current-password"></label><div class="form-grid two"><button class="btn primary" onclick="signIn()">Entrar</button><button class="btn" onclick="signUp()">Criar conta</button></div></div>`);}
function credentials(){return {email:document.getElementById("authEmail")?.value.trim(),password:document.getElementById("authPassword")?.value||""};}
async function signIn(){const {email,password}=credentials();if(!email||password.length<6)return toast("Informe e-mail e senha");try{const s=await api("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password},auth:false});s.expires_at=s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600);storeSession(s);closeModal();await initCloud();toast("Conta conectada")}catch(e){alert("Não foi possível entrar: "+e.message)}}
async function signUp(){const {email,password}=credentials();if(!email||password.length<6)return toast("Informe e-mail e senha com pelo menos 6 caracteres");try{const s=await api("/auth/v1/signup",{method:"POST",body:{email,password},auth:false});if(s.access_token){s.expires_at=s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600);storeSession(s);closeModal();await initCloud();toast("Conta criada")}else alert("Conta criada. Confirme o e-mail e depois entre.")}catch(e){alert("Não foi possível criar a conta: "+e.message)}}
async function logout(){try{await api("/auth/v1/logout",{method:"POST"})}catch{}storeSession(null);closeModal();render();toast("Sessão encerrada");}

function toggleMenu(){document.body.classList.toggle("menu-open");}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openQuickCapture();}});
matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change",()=>{if(data.settings.theme==="system")applyTheme()});
window.addEventListener("online",()=>{if(currentUser)saveLifeToCloud(true)});
window.addEventListener("offline",()=>setSync("error","Offline · salvo localmente"));

applyTheme();
render();
initCloud();
