function renderObjectives(){
  setHeader("Objetivos e metas","Direção primeiro; metas mensuráveis abaixo quando fizer sentido.",`<button class="btn primary" onclick="openObjectiveForm()">＋ Novo objetivo</button>`);
  const active=data.objectives.filter(o=>o.status!=="done");
  document.getElementById("content").innerHTML=`<div class="stack">${active.length?active.map(o=>{const gs=data.goals.filter(g=>g.objectiveId===o.id);return `<div class="card objective-card"><div class="card-head"><div><span class="eyebrow">${esc(pillarName(o.pillarId))}</span><h3>${esc(o.title)}</h3><p>${esc(o.description||"")}</p></div><button class="btn small" onclick="openObjectiveForm('${o.id}')">Editar</button></div><div class="goal-list">${gs.length?gs.map(g=>`<div class="goal-row"><div class="grow"><div class="row-between"><b>${esc(g.title)}</b><span>${Math.round(goalProgress(g))}%</span></div><div class="progress"><i style="width:${goalProgress(g)}%"></i></div><small>${esc(g.currentValue??0)} ${esc(g.unit||"")} de ${esc(g.targetValue??0)} ${esc(g.unit||"")}${g.dueDate?` · até ${fmtShort(g.dueDate)}`:""}</small></div><button class="btn small" onclick="openGoalForm('${g.id}')">Atualizar</button></div>`).join(""):'<div class="empty">Nenhuma meta vinculada.</div>'}</div><button class="text-btn" onclick="openGoalForm(null,'${o.id}')">＋ Adicionar meta</button></div>`}).join(""):'<div class="empty card">Nenhum objetivo ativo.</div>'}</div>`;
}
function openObjectiveForm(id=null,pillarId=""){
  const o=id?objective(id):null;
  openModal(o?"Editar objetivo":"Novo objetivo",`<form class="form" onsubmit="saveObjective(event,'${id||""}')"><label>Objetivo<input name="title" required value="${esc(o?.title||"")}" placeholder="Ex.: Melhorar minha condição física"></label><label>Pilar<select name="pillarId">${pillarOptions(o?.pillarId||pillarId,true)}</select></label><label>Descrição<textarea name="description" rows="3">${esc(o?.description||"")}</textarea></label><label>Status<select name="status"><option value="active" ${o?.status!=="done"?"selected":""}>Ativo</option><option value="done" ${o?.status==="done"?"selected":""}>Concluído</option><option value="paused" ${o?.status==="paused"?"selected":""}>Pausado</option></select></label><div class="modal-actions">${o?`<button type="button" class="btn" onclick="openGoalForm(null,'${o.id}')">＋ Meta</button>`:""}<button class="btn primary">Salvar</button></div></form>`);
}
function saveObjective(e,id){e.preventDefault();const f=new FormData(e.target),obj={title:String(f.get("title")||"").trim(),pillarId:String(f.get("pillarId")||"")||null,description:String(f.get("description")||"").trim(),status:String(f.get("status")||"active"),updatedAt:nowISO()};if(id)Object.assign(objective(id),obj);else data.objectives.push(Object.assign({id:uid("obj"),createdAt:nowISO()},obj));persist();closeModal();render();toast("Objetivo salvo");}
function openGoalForm(id=null,objectiveId=""){
  const g=id?goal(id):null, obj=objective(g?.objectiveId||objectiveId);
  openModal(g?"Atualizar meta":"Nova meta",`<form class="form" onsubmit="saveGoal(event,'${id||""}')"><label>Meta<input name="title" required value="${esc(g?.title||"")}" placeholder="Ex.: Chegar a 100 kg"></label><input type="hidden" name="objectiveId" value="${esc(g?.objectiveId||objectiveId||"")}"><input type="hidden" name="pillarId" value="${esc(g?.pillarId||obj?.pillarId||"")}"><div class="form-grid three"><label>Valor inicial<input name="startValue" type="number" step="any" value="${esc(g?.startValue??0)}"></label><label>Valor atual<input name="currentValue" type="number" step="any" value="${esc(g?.currentValue??0)}"></label><label>Meta<input name="targetValue" type="number" step="any" value="${esc(g?.targetValue??0)}"></label></div><div class="form-grid two"><label>Unidade<input name="unit" value="${esc(g?.unit||"")}" placeholder="kg, R$, livros..."></label><label>Prazo<input name="dueDate" type="date" value="${esc(g?.dueDate||"")}"></label></div><label>Status<select name="status"><option value="active" ${g?.status!=="done"?"selected":""}>Ativa</option><option value="done" ${g?.status==="done"?"selected":""}>Concluída</option><option value="paused" ${g?.status==="paused"?"selected":""}>Pausada</option></select></label><button class="btn primary">Salvar meta</button></form>`);
}
function saveGoal(e,id){e.preventDefault();const f=new FormData(e.target),obj={title:String(f.get("title")||"").trim(),objectiveId:String(f.get("objectiveId")||"")||null,pillarId:String(f.get("pillarId")||"")||null,startValue:Number(f.get("startValue"))||0,currentValue:Number(f.get("currentValue"))||0,targetValue:Number(f.get("targetValue"))||0,unit:String(f.get("unit")||"").trim(),dueDate:String(f.get("dueDate")||""),status:String(f.get("status")||"active"),updatedAt:nowISO()};if(id)Object.assign(goal(id),obj);else data.goals.push(Object.assign({id:uid("goal"),createdAt:nowISO()},obj));persist();closeModal();render();toast("Meta salva");}

function renderIndicatorCard(i){ const val=latestIndicatorValue(i), h=i.history||[], prev=h.length>1?h[h.length-2]?.value:null, diff=prev!==null&&prev!==undefined&&Number.isFinite(Number(val))&&Number.isFinite(Number(prev))?Number(val)-Number(prev):null; return `<div class="card indicator-card"><div class="card-head"><div><span class="label">${esc(pillarName(i.pillarId))}</span><h3>${esc(i.title)}</h3></div><button class="icon-btn" onclick="openIndicatorForm('${i.id}')">•••</button></div><div class="metric">${esc(val||"—")} <small>${esc(i.unit||"")}</small></div><p>${diff===null?"Sem comparação anterior":diff>0?`↑ ${diff} desde o registro anterior`:diff<0?`↓ ${Math.abs(diff)} desde o registro anterior`:"Sem mudança desde o registro anterior"}</p><button class="btn small" onclick="openIndicatorCheckin('${i.id}')">Atualizar indicador</button></div>`; }
function openIndicatorForm(id=null,pillarId=""){ const i=id?data.indicators.find(x=>x.id===id):null; openModal(i?"Editar indicador":"Novo indicador",`<form class="form" onsubmit="saveIndicator(event,'${id||""}')"><label>Indicador<input name="title" required value="${esc(i?.title||"")}" placeholder="Ex.: Peso"></label><div class="form-grid two"><label>Pilar<select name="pillarId" required>${pillarOptions(i?.pillarId||pillarId,false)}</select></label><label>Unidade<input name="unit" value="${esc(i?.unit||"")}" placeholder="kg, R$, %, clientes..."></label></div><label>Como interpretar<select name="direction"><option value="neutral" ${i?.direction==="neutral"?"selected":""}>Apenas acompanhar</option><option value="higher" ${i?.direction==="higher"?"selected":""}>Maior tende a ser melhor</option><option value="lower" ${i?.direction==="lower"?"selected":""}>Menor tende a ser melhor</option></select></label><button class="btn primary">Salvar indicador</button></form>`); }
function saveIndicator(e,id){e.preventDefault();const f=new FormData(e.target),obj={title:String(f.get("title")||"").trim(),pillarId:String(f.get("pillarId")||""),unit:String(f.get("unit")||"").trim(),direction:String(f.get("direction")||"neutral"),updatedAt:nowISO()};if(id)Object.assign(data.indicators.find(x=>x.id===id),obj);else data.indicators.push(Object.assign({id:uid("ind"),history:[],createdAt:nowISO()},obj));persist();closeModal();render();toast("Indicador salvo");}
function openIndicatorCheckin(id){ const i=data.indicators.find(x=>x.id===id); if(!i)return; openModal("Atualizar indicador",`<form class="form" onsubmit="saveIndicatorCheckin(event,'${id}')"><div class="auth-note"><b>${esc(i.title)}</b> · último valor: ${esc(latestIndicatorValue(i)||"—")} ${esc(i.unit||"")}</div><div class="form-grid two"><label>Data<input name="date" type="date" value="${today()}"></label><label>Novo valor<input name="value" type="number" step="any" required></label></div><label>Observação<textarea name="note" rows="3"></textarea></label><button class="btn primary">Registrar</button></form>`); }
function saveIndicatorCheckin(e,id){e.preventDefault();const f=new FormData(e.target),i=data.indicators.find(x=>x.id===id);i.history=i.history||[];i.history.push({date:String(f.get("date")||today()),value:Number(f.get("value")),note:String(f.get("note")||"").trim()});i.history.sort((a,b)=>a.date.localeCompare(b.date));i.updatedAt=nowISO();persist();closeModal();render();toast("Indicador atualizado");}

