function statusOptions(selected=""){
  return [["evolving","🟢 Evoluindo"],["stagnant","🟡 Estagnado"],["regressing","🔴 Regredindo"],["paused","⚪ Pausado"]].map(([v,l])=>`<option value="${v}" ${selected===v?"selected":""}>${l}</option>`).join("");
}
function historyPoints(history=[]){
  return history.filter(x=>Number.isFinite(Number(x.value))).slice(-12).map(x=>({date:x.date,value:Number(x.value)}));
}
function lineChart(history=[]){
  const pts=historyPoints(history);
  if(pts.length<2)return '<div class="chart-empty">O gráfico aparece após 2 registros.</div>';
  const values=pts.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=320,h=86,p=8;
  const coords=pts.map((x,i)=>({x:p+(i*(w-p*2)/(pts.length-1)),y:p+((max-x.value)/range)*(h-p*2)}));
  const points=coords.map(c=>`${c.x.toFixed(1)},${c.y.toFixed(1)}`).join(" ");
  return `<div class="mini-chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Evolução dos registros"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/>${coords.map(c=>`<circle cx="${c.x}" cy="${c.y}" r="3.2" fill="currentColor"/>`).join("")}</svg><div class="chart-range"><span>${esc(pts[0].value)}</span><span>${esc(pts[pts.length-1].value)}</span></div></div>`;
}
function renderGoalRow(g){
  const cur=goalCurrent(g),target=num(g.targetValue),unit=esc(g.unit||"");
  return `<div class="goal-row"><div class="grow"><div class="row-between"><b>${esc(g.title)}</b><span class="status-chip ${goalStatusClass(g.qualitativeStatus)}">● ${goalStatusLabel(g.qualitativeStatus)}</span></div><div class="goal-values"><strong>${esc(cur)} ${unit}</strong><span>→ alvo ${esc(target)} ${unit}${g.dueDate?` · ${fmtShort(g.dueDate)}`:""}</span></div>${lineChart(g.history)}</div><div class="row-actions"><button class="btn small primary" onclick="openGoalCheckin('${g.id}')">Check-in</button><button class="icon-btn" onclick="openGoalForm('${g.id}')">•••</button></div></div>`;
}
function renderObjectives(){
  setHeader("Objetivos e Metas","Direção qualitativa com metas numéricas e histórico real.",`<button class="btn primary" onclick="openObjectiveForm()">＋ Novo objetivo</button>`);
  const active=data.objectives.filter(o=>o.status!=="done"),orphans=data.goals.filter(g=>!g.objectiveId&&g.status!=="done");
  document.getElementById("content").innerHTML=`<div class="stack">${active.length?active.map(o=>{const gs=data.goals.filter(g=>g.objectiveId===o.id&&g.status!=="done");return `<div class="card objective-card"><div class="card-head"><div><span class="eyebrow">${esc(pillarName(o.pillarId))}</span><h3>${esc(o.title)}</h3><p>${esc(o.description||"")}</p></div><button class="btn small" onclick="openObjectiveForm('${o.id}')">Editar</button></div><div class="goal-list">${gs.length?gs.map(renderGoalRow).join(""):'<div class="empty">Nenhuma meta vinculada.</div>'}</div><button class="text-btn" onclick="openGoalForm(null,'${o.id}','${o.pillarId||""}')">＋ Adicionar meta</button></div>`}).join(""):'<div class="empty card">Nenhum objetivo ativo. Você também pode criar metas diretamente em um pilar.</div>'}</div>
  ${orphans.length?`<div class="section-title"><div><span class="eyebrow">METAS DIRETAS</span><h2>Sem objetivo vinculado</h2></div></div><div class="card list">${orphans.map(renderGoalRow).join("")}</div>`:""}`;
}
function openObjectiveForm(id=null,pillarId=""){
  const o=id?objective(id):null;
  openModal(o?"Editar objetivo":"Novo objetivo",`<form class="form" onsubmit="saveObjective(event,'${id||""}')"><label>Objetivo<input name="title" required value="${esc(o?.title||"")}" placeholder="Ex.: Melhorar minha condição física"></label><label>Pilar<select name="pillarId">${pillarOptions(o?.pillarId||pillarId,true)}</select></label><label>Descrição<textarea name="description" rows="3">${esc(o?.description||"")}</textarea></label><label>Status<select name="status"><option value="active" ${o?.status!=="done"?"selected":""}>Ativo</option><option value="done" ${o?.status==="done"?"selected":""}>Concluído</option><option value="paused" ${o?.status==="paused"?"selected":""}>Pausado</option></select></label><div class="modal-actions">${o?`<button type="button" class="btn" onclick="openGoalForm(null,'${o.id}','${o.pillarId||""}')">＋ Meta</button>`:""}<button class="btn primary">Salvar</button></div></form>`);
}
function saveObjective(e,id){e.preventDefault();const f=new FormData(e.target),obj={title:String(f.get("title")||"").trim(),pillarId:String(f.get("pillarId")||"")||null,description:String(f.get("description")||"").trim(),status:String(f.get("status")||"active"),updatedAt:nowISO()};if(id)Object.assign(objective(id),obj);else data.objectives.push(Object.assign({id:uid("obj"),createdAt:nowISO()},obj));persist();closeModal();render();toast("Objetivo salvo");}
function openGoalForm(id=null,objectiveId="",pillarId=""){
  const g=id?goal(id):null,obj=objective(g?.objectiveId||objectiveId),resolvedPillar=g?.pillarId||obj?.pillarId||pillarId||"";
  openModal(g?"Editar meta":"Nova meta",`<form class="form" onsubmit="saveGoal(event,'${id||""}')"><label>Meta<input name="title" required value="${esc(g?.title||"")}" placeholder="Ex.: Chegar a 95 kg"></label><div class="form-grid two"><label>Pilar<select name="pillarId" required>${pillarOptions(resolvedPillar,false)}</select></label><label>Objetivo <span class="hint">opcional</span><select name="objectiveId">${objectiveOptions(g?.objectiveId||objectiveId,resolvedPillar)}</select></label></div><div class="form-grid three"><label>Valor inicial<input inputmode="decimal" name="startValue" type="number" step="any" value="${esc(g?.startValue??"")}"></label><label>Valor atual<input inputmode="decimal" name="currentValue" type="number" step="any" value="${esc(g?goalCurrent(g):"")}"></label><label>Valor alvo<input inputmode="decimal" name="targetValue" type="number" step="any" required value="${esc(g?.targetValue??"")}"></label></div><div class="form-grid two"><label>Unidade<input name="unit" value="${esc(g?.unit||"")}" placeholder="kg, R$, clientes, vezes"></label><label>Prazo<input name="dueDate" type="date" value="${esc(g?.dueDate||"")}"></label></div><label>Status atual<select name="qualitativeStatus"><option value="">Sem status</option>${statusOptions(g?.qualitativeStatus||"")}</select></label><label>Situação da meta<select name="status"><option value="active" ${g?.status!=="done"?"selected":""}>Ativa</option><option value="done" ${g?.status==="done"?"selected":""}>Concluída</option></select></label><button class="btn primary">Salvar meta</button></form>`);
}
function saveGoal(e,id){
  e.preventDefault();const f=new FormData(e.target),current=Number(f.get("currentValue")),obj={title:String(f.get("title")||"").trim(),objectiveId:String(f.get("objectiveId")||"")||null,pillarId:String(f.get("pillarId")||"")||null,startValue:num(f.get("startValue")),currentValue:Number.isFinite(current)?current:0,targetValue:num(f.get("targetValue")),unit:String(f.get("unit")||"").trim(),dueDate:String(f.get("dueDate")||""),status:String(f.get("status")||"active"),qualitativeStatus:String(f.get("qualitativeStatus")||""),updatedAt:nowISO()};
  if(id){const g=goal(id),before=goalCurrent(g);Object.assign(g,obj);g.history=g.history||[];if(Number.isFinite(current)&&current!==before)g.history.push({date:today(),value:current,status:obj.qualitativeStatus,note:"Atualização da meta"});}
  else{const g=Object.assign({id:uid("goal"),history:[],createdAt:nowISO()},obj);if(Number.isFinite(current))g.history.push({date:today(),value:current,status:obj.qualitativeStatus,note:"Valor inicial"});data.goals.push(g);}
  persist();closeModal();render();toast("Meta salva");
}
function openGoalCheckin(id){
  const g=goal(id);if(!g)return;
  openModal("Check-in da meta",`<form class="form" onsubmit="saveGoalCheckin(event,'${id}')"><div class="auth-note"><b>${esc(g.title)}</b><br>Atual: ${esc(goalCurrent(g))} ${esc(g.unit||"")} · alvo: ${esc(g.targetValue)} ${esc(g.unit||"")}</div><div class="form-grid two"><label>Data<input name="date" type="date" value="${today()}"></label><label>Novo valor<input inputmode="decimal" name="value" type="number" step="any" required value="${esc(goalCurrent(g))}"></label></div><label>Como esta meta está?<select name="qualitativeStatus" required>${statusOptions(g.qualitativeStatus||"stagnant")}</select></label><label>Observação <span class="hint">opcional</span><textarea name="note" rows="3"></textarea></label><button class="btn primary">Registrar evolução</button></form>`);
}
function saveGoalCheckin(e,id){
  e.preventDefault();const f=new FormData(e.target),g=goal(id),value=Number(f.get("value")),status=String(f.get("qualitativeStatus")||"stagnant");
  g.history=g.history||[];g.history.push({date:String(f.get("date")||today()),value,status,note:String(f.get("note")||"").trim()});g.history.sort((a,b)=>a.date.localeCompare(b.date));g.currentValue=value;g.qualitativeStatus=status;g.updatedAt=nowISO();persist();closeModal();render();toast("Meta atualizada");
}
function renderIndicatorCard(i){
  const val=latestIndicatorValue(i),h=i.history||[],prev=h.length>1?h[h.length-2]?.value:null,diff=prev!==null&&Number.isFinite(Number(val))&&Number.isFinite(Number(prev))?Number(val)-Number(prev):null;
  return `<div class="card indicator-card"><div class="card-head"><div><span class="label">${esc(pillarName(i.pillarId))}</span><h3>${esc(i.title)}</h3></div><button class="icon-btn" onclick="openIndicatorForm('${i.id}')">•••</button></div><div class="metric">${esc(val===""?"—":val)} <small>${esc(i.unit||"")}</small></div>${lineChart(h)}<p>${diff===null?"Sem comparação anterior":diff>0?`↑ ${diff} desde o registro anterior`:diff<0?`↓ ${Math.abs(diff)} desde o registro anterior`:"Sem mudança desde o registro anterior"}</p><button class="btn small" onclick="openIndicatorCheckin('${i.id}')">Atualizar</button></div>`;
}
function openIndicatorForm(id=null,pillarId=""){
  const i=id?data.indicators.find(x=>x.id===id):null;
  openModal(i?"Editar indicador":"Novo indicador",`<form class="form" onsubmit="saveIndicator(event,'${id||""}')"><label>Indicador<input name="title" required value="${esc(i?.title||"")}" placeholder="Ex.: Peso"></label><div class="form-grid two"><label>Pilar<select name="pillarId" required>${pillarOptions(i?.pillarId||pillarId,false)}</select></label><label>Unidade<input name="unit" value="${esc(i?.unit||"")}" placeholder="kg, R$, %, clientes..."></label></div><label>Como interpretar<select name="direction"><option value="neutral" ${i?.direction==="neutral"?"selected":""}>Apenas acompanhar</option><option value="higher" ${i?.direction==="higher"?"selected":""}>Maior tende a ser melhor</option><option value="lower" ${i?.direction==="lower"?"selected":""}>Menor tende a ser melhor</option></select></label><button class="btn primary">Salvar indicador</button></form>`);
}
function saveIndicator(e,id){e.preventDefault();const f=new FormData(e.target),obj={title:String(f.get("title")||"").trim(),pillarId:String(f.get("pillarId")||""),unit:String(f.get("unit")||"").trim(),direction:String(f.get("direction")||"neutral"),updatedAt:nowISO()};if(id)Object.assign(data.indicators.find(x=>x.id===id),obj);else data.indicators.push(Object.assign({id:uid("ind"),history:[],createdAt:nowISO()},obj));persist();closeModal();render();toast("Indicador salvo");}
function openIndicatorCheckin(id){const i=data.indicators.find(x=>x.id===id);if(!i)return;openModal("Atualizar indicador",`<form class="form" onsubmit="saveIndicatorCheckin(event,'${id}')"><div class="auth-note"><b>${esc(i.title)}</b> · último valor: ${esc(latestIndicatorValue(i)||"—")} ${esc(i.unit||"")}</div><div class="form-grid two"><label>Data<input name="date" type="date" value="${today()}"></label><label>Novo valor<input inputmode="decimal" name="value" type="number" step="any" required></label></div><label>Observação<textarea name="note" rows="3"></textarea></label><button class="btn primary">Registrar</button></form>`);}
function saveIndicatorCheckin(e,id){e.preventDefault();const f=new FormData(e.target),i=data.indicators.find(x=>x.id===id);i.history=i.history||[];i.history.push({date:String(f.get("date")||today()),value:Number(f.get("value")),note:String(f.get("note")||"").trim()});i.history.sort((a,b)=>a.date.localeCompare(b.date));i.updatedAt=nowISO();persist();closeModal();render();toast("Indicador atualizado");}
