
function renderReviews(){
  setHeader("Revisões","Percepção + dados + contexto. Sem transformar sua vida em uma nota única.",`<button class="btn primary" onclick="openReviewForm()">＋ Nova revisão</button>`);
  const arr=[...data.reviews].sort((a,b)=>b.date.localeCompare(a.date));
  document.getElementById("content").innerHTML=`<div class="card list">${arr.length?arr.map(r=>`<div class="review-row"><div class="review-status ${trendClass(r.trend)}"></div><div class="grow"><div class="row-between"><b>${r.pillarId?esc(pillarName(r.pillarId)):"Revisão geral da vida"}</b><span>${fmtDate(r.date)}</span></div><small>${trendLabel(r.trend)}${r.perception?` · percepção ${r.perception}/10`:""}</small><p>${r.better?`Melhorou: ${esc(r.better)}`:""}${r.worse?` · Piorou: ${esc(r.worse)}`:""}</p><p><b>Ajuste:</b> ${esc(r.adjust||"—")}</p></div></div>`).join(""):'<div class="empty">Nenhuma revisão registrada.</div>'}</div>`;
}
function openReviewForm(pillarId=""){openModal(pillarId?`Revisar ${pillarName(pillarId)}`:"Nova revisão",`<form class="form" onsubmit="saveReview(event)"><div class="form-grid two"><label>Escopo<select name="pillarId"><option value="">Vida como um todo</option>${pillarOptions(pillarId,false)}</select></label><label>Data<input name="date" type="date" value="${today()}"></label></div><div class="form-grid two"><label>Situação<select name="trend"><option value="improving">Melhorando</option><option value="stable" selected>Estável</option><option value="attention">Atenção</option></select></label><label>Minha percepção (0–10)<input name="perception" type="number" min="0" max="10" step="1"></label></div><label>O que melhorou?<textarea name="better" rows="3"></textarea></label><label>O que piorou ou travou?<textarea name="worse" rows="3"></textarea></label><label>O que preciso ajustar?<textarea name="adjust" rows="3"></textarea></label><label>Acontecimento ou contexto importante<textarea name="context" rows="3"></textarea></label><button class="btn primary">Salvar revisão</button></form>`);}
function saveReview(e){e.preventDefault();const f=new FormData(e.target);data.reviews.push({id:uid("rev"),pillarId:String(f.get("pillarId")||"")||null,date:String(f.get("date")||today()),trend:String(f.get("trend")||"stable"),perception:Number(f.get("perception"))||null,better:String(f.get("better")||"").trim(),worse:String(f.get("worse")||"").trim(),adjust:String(f.get("adjust")||"").trim(),context:String(f.get("context")||"").trim(),createdAt:nowISO()});persist();closeModal();render();toast("Revisão registrada");}

function renderTimeline(){
  setHeader("Linha do tempo","Acontecimentos, decisões e contexto que explicam sua trajetória.",`<button class="btn" onclick="openTimelineForm('event')">＋ Acontecimento</button><button class="btn primary" onclick="openTimelineForm('decision')">＋ Decisão</button>`);
  const arr=[...data.timeline].sort((a,b)=>b.date.localeCompare(a.date));
  document.getElementById("content").innerHTML=`<div class="timeline">${arr.length?arr.map(x=>`<div class="timeline-item"><div class="timeline-mark ${x.type}"></div><div class="card"><div class="row-between"><span class="eyebrow">${x.type==="decision"?"DECISÃO":"ACONTECIMENTO"}</span><span>${fmtDate(x.date)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.notes||x.reason||"")}</p><small>${(x.pillarIds||[]).map(pillarName).map(esc).join(" · ")||"Vida geral"}${x.reviewDate?` · revisar em ${fmtShort(x.reviewDate)}`:""}</small></div></div>`).join(""):'<div class="empty card">Sua linha do tempo começa quando você registrar algo importante.</div>'}</div>`;
}
function pillarCheckboxes(selected=[]){return activePillars().map(p=>`<label class="check"><input type="checkbox" name="pillarIds" value="${p.id}" ${selected.includes(p.id)?"checked":""}><span>${esc(p.name)}</span></label>`).join("");}
function openTimelineForm(type="event"){openModal(type==="decision"?"Registrar decisão":"Registrar acontecimento",`<form class="form" onsubmit="saveTimeline(event,'${type}')"><div class="form-grid two"><label>${type==="decision"?"Decisão":"Acontecimento"}<input name="title" required></label><label>Data<input name="date" type="date" value="${today()}"></label></div><label>${type==="decision"?"Motivo / contexto":"O que aconteceu?"}<textarea name="notes" rows="4"></textarea></label><div><span class="label">Pilares relacionados</span><div class="check-grid">${pillarCheckboxes()}</div></div>${type==="decision"?'<label>Quando quero revisar esta decisão? <span class="hint">opcional</span><input name="reviewDate" type="date"></label>':''}<button class="btn primary">Registrar</button></form>`);}
function saveTimeline(e,type){e.preventDefault();const f=new FormData(e.target);data.timeline.push({id:uid("time"),type,title:String(f.get("title")||"").trim(),date:String(f.get("date")||today()),notes:String(f.get("notes")||"").trim(),pillarIds:f.getAll("pillarIds"),reviewDate:String(f.get("reviewDate")||""),createdAt:nowISO()});persist();closeModal();render();toast(type==="decision"?"Decisão registrada":"Acontecimento registrado");}

function renderInbox(){setHeader("Inbox","Capture primeiro. Decida onde isso pertence depois.",`<button class="btn primary" onclick="openQuickCapture()">＋ Capturar</button>`);document.getElementById("content").innerHTML=`<div class="card list">${data.inbox.length?data.inbox.map(x=>`<div class="list-row inbox-row"><div><b>${esc(x.text)}</b><small>${new Date(x.createdAt).toLocaleString("pt-BR")}</small></div><div class="row-actions"><button class="btn small" onclick="inboxToTimeline('${x.id}')">Acontecimento</button><button class="btn small" onclick="inboxToObjective('${x.id}')">Objetivo</button><button class="icon-btn danger-text" onclick="deleteInbox('${x.id}')">×</button></div></div>`).join(""):'<div class="empty">Inbox vazia.</div>'}</div>`;}
function openQuickCapture(){openModal("Captura rápida",`<form class="form" onsubmit="saveQuickCapture(event)"><label>O que você quer guardar?<textarea name="text" rows="5" required autofocus placeholder="Ideia, algo que aconteceu, decisão para pensar, objetivo..."></textarea></label><button class="btn primary">Enviar para Inbox</button></form>`);}
function saveQuickCapture(e){e.preventDefault();const f=new FormData(e.target);data.inbox.unshift({id:uid("in"),text:String(f.get("text")||"").trim(),createdAt:nowISO()});persist();closeModal();render();toast("Capturado");}
function deleteInbox(id){data.inbox=data.inbox.filter(x=>x.id!==id);persist();render();}
function inboxToTimeline(id){const x=data.inbox.find(v=>v.id===id);if(!x)return;data.timeline.push({id:uid("time"),type:"event",title:x.text,date:today(),notes:"",pillarIds:[],reviewDate:"",createdAt:nowISO()});deleteInbox(id);toast("Movido para a linha do tempo");}
function inboxToObjective(id){const x=data.inbox.find(v=>v.id===id);if(!x)return;data.objectives.push({id:uid("obj"),title:x.text,pillarId:null,description:"",status:"active",createdAt:nowISO(),updatedAt:nowISO()});deleteInbox(id);toast("Transformado em objetivo");}

function buildLifeTXT(){
  const lines=[]; const push=(s="")=>lines.push(s);
  push("MINHA VIDA — RESUMO ESTRUTURADO"); push(`Gerado em: ${new Date().toLocaleString("pt-BR")}`); push(`Versão: ${APP_VERSION}`); push("");
  push("== PLANEJAMENTO ATUAL =="); ["year","quarter","month","week"].forEach(t=>{const p=data.plans[planKey(t)];push(`${periodLabel(t)}:`);push(`Foco: ${p?.focus||"não definido"}`);push(`Prioridades: ${p?.priorities||"não definidas"}`);if(t==="week")push(`Check-ins esperados: ${p?.checkins||"não definidos"}`);push("");});
  push("== PILARES =="); activePillars().forEach(p=>{const r=latestReview(p.id);push(`\n[${p.name}]`);push(`Situação: ${trendLabel(r?.trend)}`);if(r?.perception)push(`Percepção: ${r.perception}/10`);if(r?.better)push(`Melhorou: ${r.better}`);if(r?.worse)push(`Piorou/travou: ${r.worse}`);if(r?.adjust)push(`Ajuste: ${r.adjust}`);const inds=data.indicators.filter(i=>i.pillarId===p.id);if(inds.length){push("Indicadores:");inds.forEach(i=>push(`- ${i.title}: ${latestIndicatorValue(i)} ${i.unit||""}`));}const gs=data.goals.filter(g=>g.pillarId===p.id&&g.status!=="done");if(gs.length){push("Metas ativas:");gs.forEach(g=>push(`- ${g.title}: ${g.currentValue}/${g.targetValue} ${g.unit||""} (${Math.round(goalProgress(g))}%)`));}const hs=data.habits.filter(h=>h.pillarId===p.id);if(hs.length){push("Hábitos acompanhados:");hs.forEach(h=>{const c=(h.checkins||[]).slice(-1)[0];push(`- ${h.title}: último check-in ${c?`${c.value}/${h.target}`:"não registrado"}`);});}});
  push("\n== PROJETOS ATIVOS =="); data.projects.filter(p=>p.status!=="done").forEach(p=>push(`- ${p.title} [${pillarName(p.pillarId)}]: ${p.progress||0}%${p.dueDate?` · prazo ${p.dueDate}`:""}`));
  push("\n== ACONTECIMENTOS E DECISÕES RECENTES =="); [...data.timeline].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).forEach(x=>push(`- ${x.date} · ${x.type==="decision"?"DECISÃO":"ACONTECIMENTO"}: ${x.title}${x.notes?` — ${x.notes}`:""}`));
  push("\n== OBJETIVOS SEM PILAR =="); data.objectives.filter(o=>!o.pillarId&&o.status!=="done").forEach(o=>push(`- ${o.title}`));
  push("\n== INBOX =="); data.inbox.forEach(x=>push(`- ${x.text}`));
  push("\nObservação: este arquivo é um resumo gerado pelo sistema para leitura humana ou uso por um bot externo. Nenhuma decisão deve ser executada automaticamente a partir dele.");
  return lines.join("\n");
}
function renderExport(){setHeader("Resumo TXT","Uma saída estruturada do sistema para leitura ou análise por um bot externo.",`<button class="btn primary" onclick="downloadTXT()">Baixar TXT</button>`);const txt=buildLifeTXT();document.getElementById("content").innerHTML=`<div class="card"><div class="row-between"><div><b>Prévia do resumo</b><p class="muted">Nenhuma IA roda dentro do Minha Vida.</p></div><button class="btn" onclick="copyTXT()">Copiar</button></div><pre class="txt-preview">${esc(txt)}</pre></div>`;}
function downloadTXT(){const blob=new Blob(["\ufeff",buildLifeTXT()],{type:"text/plain;charset=utf-8"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`minha-vida-resumo-${today()}.txt`;a.click();URL.revokeObjectURL(u);toast("Resumo TXT gerado");}
async function copyTXT(){try{await navigator.clipboard.writeText(buildLifeTXT());toast("Resumo copiado")}catch{toast("Não foi possível copiar")}}
