let reviewTab="monthly";
function setReviewTab(tab){reviewTab=tab;renderReviews();}
function monthlyReviews(){return [...data.reviews].filter(r=>r.kind==="monthly").sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
function pillarReviews(){return [...data.reviews].filter(r=>r.kind==="pillar").sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
function reviewOneLine(r){return r.summary||r.adjust||r.better||r.context||r.whatHappened||"Sem resumo.";}
function renderReviews(){
  setHeader("Revisões","Contexto, impacto e decisões preservados ao longo do tempo.",`<button class="btn" onclick="openPillarReviewForm()">＋ Revisar pilar</button><button class="btn primary" onclick="openMonthlyReviewForm()">Fechar mês</button>`);
  const monthly=monthlyReviews(),pillars=pillarReviews(),history=[...data.timeline].sort((a,b)=>String(b.date).localeCompare(String(a.date)));
  let body="";
  if(reviewTab==="monthly")body=`<div class="review-list">${monthly.length?monthly.map(r=>`<button class="review-history-card card" onclick="openReviewDetail('${r.id}')"><div class="row-between"><div><span class="eyebrow">REVISÃO MENSAL</span><h3>${esc(new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(`${r.date}T12:00:00`)))}</h3></div><span class="review-score">${esc(r.rating||"—")}/10</span></div><p>${esc(reviewOneLine(r))}</p><small>${fmtDate(r.date)}</small></button>`).join(""):'<div class="empty card">Nenhuma revisão mensal fechada. Ao fechar o mês, ela entra automaticamente no histórico.</div>'}</div>`;
  if(reviewTab==="pillar")body=`<div class="review-list">${pillars.length?pillars.map(r=>`<button class="review-history-card card" onclick="openReviewDetail('${r.id}')"><div class="row-between"><div><span class="eyebrow">${esc(pillarName(r.pillarId))}</span><h3>${trendLabel(r.trend)}</h3></div><span class="status-chip ${trendClass(r.trend)}">● ${trendLabel(r.trend)}</span></div><p>${esc(reviewOneLine(r))}</p><small>${fmtDate(r.date)}${r.perception?` · percepção ${r.perception}/10`:""}</small></button>`).join(""):'<div class="empty card">Nenhuma revisão de pilar registrada.</div>'}</div>`;
  if(reviewTab==="history")body=`<div class="history-actions"><button class="btn" onclick="openTimelineForm('event')">＋ Acontecimento</button><button class="btn" onclick="openTimelineForm('decision')">＋ Decisão</button></div><div class="timeline">${history.length?history.map(x=>`<div class="timeline-item"><div class="timeline-mark ${x.type}"></div><button class="card timeline-card" onclick="${x.sourceReviewId?`openReviewDetail('${x.sourceReviewId}')`:"void(0)"}"><div class="row-between"><span class="eyebrow">${x.type==="decision"?"DECISÃO":x.type==="review"?"REVISÃO MENSAL":"ACONTECIMENTO"}</span><span>${fmtDate(x.date)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.notes||"")}</p><small>${(x.pillarIds||[]).map(pillarName).map(esc).join(" · ")||"Vida geral"}</small></button></div>`).join(""):'<div class="empty card">O histórico começa com revisões, acontecimentos e decisões.</div>'}</div>`;
  document.getElementById("content").innerHTML=`<div class="segmented"><button class="${reviewTab==="monthly"?"active":""}" onclick="setReviewTab('monthly')">Mensais</button><button class="${reviewTab==="pillar"?"active":""}" onclick="setReviewTab('pillar')">Por pilar</button><button class="${reviewTab==="history"?"active":""}" onclick="setReviewTab('history')">Histórico</button></div>${body}`;
}
function weeklyMonthContext(month=monthKey()){
  const weeks=data.weeklyCheckins.filter(x=>String(x.date||x.weekStart).startsWith(month));
  if(!weeks.length)return "Ainda não há check-ins semanais neste mês.";
  return weeks.map(x=>`• Semana ${fmtShort(x.weekStart)}: ${x.worked||"sem aprendizado registrado"} · próximo foco: ${x.nextFocus||"—"}`).join("\n");
}

function monthlyPlanReviewContext(month){
  const p=data.plans[`month:${month}`]||{},targets=Object.entries(p.goalTargets||{});
  const lines=[];
  if(p.focus)lines.push(`Foco: ${p.focus}`);
  if(p.successDefinition)lines.push(`Um bom mês seria: ${p.successDefinition}`);
  if(p.context)lines.push(`Contexto previsto: ${p.context}`);
  targets.forEach(([id,target])=>{const g=goal(id);if(g)lines.push(`• ${g.title}: ${goalCurrent(g)} ${g.unit||""} · marco planejado ${target} ${g.unit||""}`);});
  return lines.join("\n")||"Este mês não teve planejamento mensal estruturado.";
}
function openMonthlyReviewForm(date=today()){
  const month=monthKey(date),existing=data.reviews.find(r=>r.kind==="monthly"&&String(r.date).startsWith(month));
  openModal(existing?"Editar revisão mensal":"Fechar revisão mensal",`<form class="form" onsubmit="saveMonthlyReview(event,'${existing?.id||""}')"><div class="review-month-head"><div><span class="eyebrow">REVISÃO MENSAL</span><h3>${esc(new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(`${month}-15T12:00:00`)))}</h3></div><label>Nota geral<input inputmode="numeric" name="rating" type="number" min="0" max="10" step="1" required value="${esc(existing?.rating??"")}"></label></div><div class="review-plan-context"><span class="eyebrow">O QUE FOI PLANEJADO</span><pre>${esc(monthlyPlanReviewContext(month))}</pre></div><label>Resumo em uma linha<input name="summary" required maxlength="160" value="${esc(existing?.summary||"")}" placeholder="A frase que resume este mês."></label><label><b>1. O que aconteceu</b><span class="hint">Contexto real do mês: trabalho, família, eventos e mudanças.</span><textarea name="whatHappened" rows="4" required>${esc(existing?.whatHappened||"")}</textarea></label><label><b>2. O que impactou</b><span class="hint">Compare o planejado com o que realmente aconteceu. O que ajudou ou atrapalhou?</span><textarea name="whatImpacted" rows="4" required>${esc(existing?.whatImpacted||"")}</textarea></label><label><b>3. O que ajusto</b><span class="hint">Uma ou duas decisões concretas que seguem para o próximo planejamento.</span><textarea name="whatAdjust" rows="4" required>${esc(existing?.whatAdjust||"")}</textarea></label><div class="auth-note"><b>Check-ins que alimentam esta revisão</b><pre class="context-preview">${esc(weeklyMonthContext(month))}</pre></div><input type="hidden" name="date" value="${month}-${month===monthKey()?today().slice(8,10):"28"}"><button class="btn primary">Fechar revisão mensal</button></form>`,true);
}
function saveMonthlyReview(e,id){
  e.preventDefault();const f=new FormData(e.target),obj={kind:"monthly",pillarId:null,date:String(f.get("date")||today()),rating:Number(f.get("rating")),summary:String(f.get("summary")||"").trim(),whatHappened:String(f.get("whatHappened")||"").trim(),whatImpacted:String(f.get("whatImpacted")||"").trim(),whatAdjust:String(f.get("whatAdjust")||"").trim(),closed:true,updatedAt:nowISO()};
  let r;if(id){r=data.reviews.find(x=>x.id===id);Object.assign(r,obj);}else{r=Object.assign({id:uid("rev"),createdAt:nowISO()},obj);data.reviews.push(r);}
  let t=data.timeline.find(x=>x.sourceReviewId===r.id);const title=`Revisão mensal · ${new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(`${r.date}T12:00:00`))}`;if(t)Object.assign(t,{date:r.date,title,notes:r.summary});else data.timeline.push({id:uid("time"),type:"review",title,date:r.date,notes:r.summary,pillarIds:[],sourceReviewId:r.id,createdAt:nowISO()});
  persist();closeModal();reviewTab="monthly";render();toast("Revisão mensal fechada");
}
function openPillarReviewForm(pillarId=""){
  openModal("Revisão de pilar",`<form class="form" onsubmit="savePillarReview(event)"><div class="form-grid two"><label>Pilar<select name="pillarId" required><option value="">Selecione</option>${pillarOptions(pillarId,false)}</select></label><label>Data<input name="date" type="date" value="${today()}"></label></div><div class="form-grid two"><label>Situação<select name="trend"><option value="improving">🟢 Evoluindo</option><option value="stable" selected>🟡 Estável</option><option value="attention">🔴 Atenção</option></select></label><label>Minha percepção (0–10)<input inputmode="numeric" name="perception" type="number" min="0" max="10" step="1"></label></div><label>O que melhorou?<textarea name="better" rows="3"></textarea></label><label>O que precisa de atenção?<textarea name="worse" rows="3"></textarea></label><label>O que vou ajustar?<textarea name="adjust" rows="3"></textarea></label><button class="btn primary">Salvar revisão do pilar</button></form>`);
}
function savePillarReview(e){e.preventDefault();const f=new FormData(e.target);data.reviews.push({id:uid("rev"),kind:"pillar",pillarId:String(f.get("pillarId")),date:String(f.get("date")||today()),trend:String(f.get("trend")||"stable"),perception:Number(f.get("perception"))||null,better:String(f.get("better")||"").trim(),worse:String(f.get("worse")||"").trim(),adjust:String(f.get("adjust")||"").trim(),closed:true,createdAt:nowISO()});persist();closeModal();reviewTab="pillar";render();toast("Revisão do pilar registrada");}
function openReviewForm(pillarId=""){return pillarId?openPillarReviewForm(pillarId):openMonthlyReviewForm();}
function openReviewDetail(id){
  const r=data.reviews.find(x=>x.id===id);if(!r)return;
  if(r.kind==="monthly")openModal("Revisão mensal",`<div class="review-detail"><div class="row-between"><div><span class="eyebrow">${fmtDate(r.date)}</span><h2>${esc(r.summary||"Revisão mensal")}</h2></div><span class="review-score">${esc(r.rating||"—")}/10</span></div><section><span>O QUE ACONTECEU</span><p>${esc(r.whatHappened||"—")}</p></section><section><span>O QUE IMPACTOU</span><p>${esc(r.whatImpacted||"—")}</p></section><section><span>O QUE AJUSTO</span><p>${esc(r.whatAdjust||"—")}</p></section><button class="btn" onclick="openMonthlyReviewForm('${r.date}')">Editar revisão</button></div>`);
  else openModal(`Revisão · ${pillarName(r.pillarId)}`,`<div class="review-detail"><div class="row-between"><div><span class="eyebrow">${fmtDate(r.date)}</span><h2>${trendLabel(r.trend)}</h2></div><span class="review-score">${esc(r.perception||"—")}/10</span></div><section><span>MELHOROU</span><p>${esc(r.better||"—")}</p></section><section><span>ATENÇÃO</span><p>${esc(r.worse||"—")}</p></section><section><span>AJUSTE</span><p>${esc(r.adjust||"—")}</p></section></div>`);
}
function renderTimeline(){reviewTab="history";showPage("reviews");}
function pillarCheckboxes(selected=[]){return activePillars().map(p=>`<label class="check"><input type="checkbox" name="pillarIds" value="${p.id}" ${selected.includes(p.id)?"checked":""}><span>${esc(p.name)}</span></label>`).join("");}
function openTimelineForm(type="event"){openModal(type==="decision"?"Registrar decisão":"Registrar acontecimento",`<form class="form" onsubmit="saveTimeline(event,'${type}')"><div class="form-grid two"><label>${type==="decision"?"Decisão":"Acontecimento"}<input name="title" required></label><label>Data<input name="date" type="date" value="${today()}"></label></div><label>${type==="decision"?"Motivo / contexto":"O que aconteceu?"}<textarea name="notes" rows="4"></textarea></label><div><span class="label">Pilares relacionados</span><div class="check-grid">${pillarCheckboxes()}</div></div>${type==="decision"?'<label>Quando quero revisar esta decisão? <span class="hint">opcional</span><input name="reviewDate" type="date"></label>':""}<button class="btn primary">Registrar</button></form>`);}
function saveTimeline(e,type){e.preventDefault();const f=new FormData(e.target);data.timeline.push({id:uid("time"),type,title:String(f.get("title")||"").trim(),date:String(f.get("date")||today()),notes:String(f.get("notes")||"").trim(),pillarIds:f.getAll("pillarIds"),reviewDate:String(f.get("reviewDate")||""),createdAt:nowISO()});persist();closeModal();reviewTab="history";render();toast(type==="decision"?"Decisão registrada":"Acontecimento registrado");}

function renderInbox(){setHeader("Inbox","Capture primeiro. Organize quando fizer sentido.",`<button class="btn primary" onclick="openQuickCapture()">＋ Capturar</button>`);document.getElementById("content").innerHTML=`<div class="card list">${data.inbox.length?data.inbox.map(x=>`<div class="list-row inbox-row"><div><b>${esc(x.text)}</b><small>${new Date(x.createdAt).toLocaleString("pt-BR")}</small></div><div class="row-actions"><button class="btn small" onclick="inboxToTimeline('${x.id}')">Acontecimento</button><button class="btn small" onclick="inboxToObjective('${x.id}')">Objetivo</button><button class="icon-btn danger-text" onclick="deleteInbox('${x.id}')">×</button></div></div>`).join(""):'<div class="empty">Inbox vazia.</div>'}</div>`;}
function openQuickCapture(){openModal("Captura rápida",`<form class="form" onsubmit="saveQuickCapture(event)"><label>O que você quer guardar?<textarea name="text" rows="5" required autofocus placeholder="Ideia, acontecimento, decisão, objetivo..."></textarea></label><button class="btn primary">Enviar para Inbox</button></form>`);}
function saveQuickCapture(e){e.preventDefault();const f=new FormData(e.target);data.inbox.unshift({id:uid("in"),text:String(f.get("text")||"").trim(),createdAt:nowISO()});persist();closeModal();render();toast("Capturado");}
function deleteInbox(id){data.inbox=data.inbox.filter(x=>x.id!==id);persist();render();}
function inboxToTimeline(id){const x=data.inbox.find(v=>v.id===id);if(!x)return;data.timeline.push({id:uid("time"),type:"event",title:x.text,date:today(),notes:"",pillarIds:[],reviewDate:"",createdAt:nowISO()});deleteInbox(id);toast("Movido para o histórico");}
function inboxToObjective(id){const x=data.inbox.find(v=>v.id===id);if(!x)return;data.objectives.push({id:uid("obj"),title:x.text,pillarId:null,description:"",status:"active",createdAt:nowISO(),updatedAt:nowISO()});deleteInbox(id);toast("Transformado em objetivo");}

function buildLifeTXT(){
  const lines=[],push=(s="")=>lines.push(s);push("MINHA VIDA — RESUMO ESTRUTURADO");push(`Gerado em: ${new Date().toLocaleString("pt-BR")}`);push(`Versão: ${APP_VERSION}`);push("");
  const month=data.plans[planKey("month")]||{},week=data.plans[planKey("week")]||{};push("== DIREÇÃO ATUAL ==");push(`Foco do mês: ${month.focus||"não definido"}`);push(`Foco da semana: ${week.focus||"não definido"}`);push("");
  push("== PILARES ==");activePillars().forEach(p=>{const st=pillarDerivedStatus(p.id);push(`\n[${p.name}] ${st.label}`);data.goals.filter(g=>g.pillarId===p.id&&g.status!=="done").forEach(g=>push(`- ${g.title}: ${goalCurrent(g)} ${g.unit||""} → ${g.targetValue} ${g.unit||""} · ${goalStatusLabel(g.qualitativeStatus)}`));data.indicators.filter(i=>i.pillarId===p.id).forEach(i=>push(`- ${i.title}: ${latestIndicatorValue(i)} ${i.unit||""}`));});
  push("\n== CHECK-INS SEMANAIS RECENTES ==");[...data.weeklyCheckins].sort((a,b)=>String(b.weekStart).localeCompare(String(a.weekStart))).slice(0,8).forEach(x=>push(`- ${x.weekStart}: funcionou: ${x.worked||"—"} · próximo foco: ${x.nextFocus||"—"}`));
  push("\n== REVISÕES MENSAIS ==");monthlyReviews().slice(0,6).forEach(r=>push(`- ${r.date} · ${r.rating}/10 · ${r.summary}\n  Aconteceu: ${r.whatHappened}\n  Impactou: ${r.whatImpacted}\n  Ajuste: ${r.whatAdjust}`));
  push("\n== HISTÓRICO RECENTE ==");[...data.timeline].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,20).forEach(x=>push(`- ${x.date} · ${x.title}: ${x.notes||""}`));
  push("\nObservação: resumo para leitura humana ou análise externa. O Minha Vida não executa decisões automaticamente.");return lines.join("\n");
}
function openExportModal(){openModal("Resumo TXT",`<div class="form"><div class="auth-note">Saída técnica opcional para leitura ou análise externa.</div><pre class="txt-preview">${esc(buildLifeTXT())}</pre><div class="modal-actions"><button class="btn" onclick="copyTXT()">Copiar</button><button class="btn primary" onclick="downloadTXT()">Baixar TXT</button></div></div>`);}
function renderExport(){openExportModal();showPage("home");}
function downloadTXT(){const blob=new Blob(["\ufeff",buildLifeTXT()],{type:"text/plain;charset=utf-8"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`minha-vida-resumo-${today()}.txt`;a.click();URL.revokeObjectURL(u);toast("Resumo TXT gerado");}
async function copyTXT(){try{await navigator.clipboard.writeText(buildLifeTXT());toast("Resumo copiado")}catch{toast("Não foi possível copiar")}}
