const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SUPABASE_ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')||'';
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const MS_CLIENT_ID=Deno.env.get('MICROSOFT_CLIENT_ID')||'';
const MS_CLIENT_SECRET=Deno.env.get('MICROSOFT_CLIENT_SECRET')||'';
const TOKEN_KEY=Deno.env.get('GOOGLE_TOKEN_ENCRYPTION_KEY')||'';
const APP_URL='https://meuplannerdigital.vercel.app/';
const REDIRECT_URI=`${SUPABASE_URL}/functions/v1/microsoft-todo`;
const SCOPES='openid profile email offline_access User.Read Tasks.ReadWrite';
const enc=new TextEncoder(),dec=new TextDecoder();
function cors(req:Request){const o=req.headers.get('origin')||'',app=new URL(APP_URL).origin,a=o===app||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(o);return {'Access-Control-Allow-Origin':a?o:app,'Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Vary':'Origin'}}
function json(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
async function parse(r:Response){const t=await r.text();let v:any=null;try{v=t?JSON.parse(t):null}catch{v=t}if(!r.ok){const e:any=new Error(typeof v==='string'?v:(v?.error?.message||v?.error_description||v?.error||`Erro ${r.status}`));e.status=r.status;throw e}return v}
async function admin(path:string,init:RequestInit={}){return parse(await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',...(init.headers||{})}}))}
async function authUser(req:Request){const a=req.headers.get('authorization')||'';if(!a.toLowerCase().startsWith('bearer '))return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:a}});return r.ok?await r.json():null}
function bytesToB64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function b64bytes(v:string){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function aesKey(){const raw=b64bytes(TOKEN_KEY);if(raw.byteLength!==32)throw new Error('Chave de criptografia inválida');return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt'])}
async function encryptToken(token:string){const iv=crypto.getRandomValues(new Uint8Array(12));const clear=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(token));return {encrypted_refresh_token:bytesToB64(new Uint8Array(clear)),refresh_token_iv:bytesToB64(iv)}}
async function decryptToken(row:any){const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64bytes(row.refresh_token_iv)},await aesKey(),b64bytes(row.encrypted_refresh_token));return dec.decode(clear)}
async function signState(payload:any){const data=bytesToB64(enc.encode(JSON.stringify(payload)));const key=await crypto.subtle.importKey('raw',enc.encode(SERVICE_KEY),'HMAC',{hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(data));return `${data}.${bytesToB64(new Uint8Array(sig))}`}
async function verifyState(state:string){const [data,sig]=state.split('.');if(!data||!sig)throw new Error('Estado OAuth inválido');const key=await crypto.subtle.importKey('raw',enc.encode(SERVICE_KEY),'HMAC',{hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,b64bytes(sig),enc.encode(data));if(!ok)throw new Error('Estado OAuth inválido');const p=JSON.parse(dec.decode(b64bytes(data)));if(!p?.userId||!p?.exp||Date.now()>p.exp)throw new Error('Autorização expirada');return p}
async function token(body:URLSearchParams){return parse(await fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}))}
async function accessToken(row:any){const t:any=await token(new URLSearchParams({client_id:MS_CLIENT_ID,client_secret:MS_CLIENT_SECRET,refresh_token:await decryptToken(row),grant_type:'refresh_token',scope:SCOPES}));return t.access_token}
async function graph(tok:string,path:string,init:RequestInit={}){return parse(await fetch(`https://graph.microsoft.com/v1.0${path}`,{...init,headers:{Authorization:`Bearer ${tok}`,'Content-Type':'application/json',...(init.headers||{})}}))}
async function connection(userId:string){const rows:any=await admin(`microsoft_todo_connections?user_id=eq.${encodeURIComponent(userId)}&select=*`);return Array.isArray(rows)?rows[0]||null:null}
async function ensureList(tok:string,row:any){if(row.todo_list_id)return row.todo_list_id;const lists:any=await graph(tok,'/me/todo/lists');let list=(lists.value||[]).find((x:any)=>x.displayName==='Meu Planner Digital');if(!list)list=await graph(tok,'/me/todo/lists',{method:'POST',body:JSON.stringify({displayName:'Meu Planner Digital'})});await admin(`microsoft_todo_connections?user_id=eq.${encodeURIComponent(row.user_id)}`,{method:'PATCH',body:JSON.stringify({todo_list_id:list.id,updated_at:new Date().toISOString()})});return list.id}
function brToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function weekday(date:string){const d=new Date(`${date}T12:00:00-03:00`);const js=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',weekday:'short'}).formatToParts(d).find(x=>x.type==='weekday')?.value==='Sun'?0:d.getDay());return js===0?7:js}
function scheduled(h:any,date:string){if(h.archived||h.paused)return false;if(h.pauseUntil&&date<=h.pauseUntil)return false;if(h.createdAt&&date<h.createdAt)return false;const w=weekday(date);if(h.freqType==='weekdays')return w<=5;if(h.freqType==='specific')return (h.specificDays||[]).map(Number).includes(w);return true}
function logValue(state:any,id:string,date:string){const v=state.habitLogs?.[`${id}_${date}`];return Number(typeof v==='object'?v?.value:v)||0}
function taskPayload(t:any){const body:any={title:t.name||'Tarefa',body:{contentType:'text',content:`Meu Planner Digital\nTASK:${t.id}`},status:t.status==='done'?'completed':'notStarted'};if(t.date)body.dueDateTime={dateTime:`${String(t.date).slice(0,10)}T23:59:00.0000000`,timeZone:'America/Sao_Paulo'};return body}
function habitPayload(h:any,date:string,done:boolean){return {title:`🔁 ${h.name||'Hábito'}`,body:{contentType:'text',content:`Meu Planner Digital\nHABIT:${h.id}\nDATE:${date}`},status:done?'completed':'notStarted',dueDateTime:{dateTime:`${date}T23:59:00.0000000`,timeZone:'America/Sao_Paulo'}}}
async function syncUser(userId:string){const row:any=await connection(userId);if(!row)throw new Error('Microsoft To Do ainda não está conectado.');const tok=await accessToken(row),listId=await ensureList(tok,row);const rows:any=await admin(`planner_state?user_id=eq.${encodeURIComponent(userId)}&select=state`),state=rows?.[0]?.state||{};state.tasks=Array.isArray(state.tasks)?state.tasks:[];state.habits=Array.isArray(state.habits)?state.habits:[];state.habitLogs=state.habitLogs&&typeof state.habitLogs==='object'?state.habitLogs:{};let created=0,updated=0,pulled=0;
 for(let i=0;i<state.tasks.length;i++){let t=state.tasks[i];if(!t?.id)continue;let remote:any=null;if(t.microsoftTodoId){try{remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(t.microsoftTodoId)}`);if(remote.status==='completed'&&t.status!=='done'){t={...t,status:'done',completedAt:brToday(),updatedAt:new Date().toISOString()};pulled++}}catch(e){if((e as any).status!==404)throw e;t={...t,microsoftTodoId:null}}}const payload=taskPayload(t);if(t.microsoftTodoId){remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(t.microsoftTodoId)}`,{method:'PATCH',body:JSON.stringify(payload)});updated++}else{remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks`,{method:'POST',body:JSON.stringify(payload)});created++}state.tasks[i]={...t,microsoftTodoId:remote.id,microsoftTodoSyncedAt:new Date().toISOString()}}
 const today=brToday();for(let i=0;i<state.habits.length;i++){let h=state.habits[i];if(!h?.id||!scheduled(h,today))continue;const done=logValue(state,h.id,today)>=Number(h.target||1);let remote:any=null;if(h.microsoftTodoDate===today&&h.microsoftTodoId){try{remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(h.microsoftTodoId)}`);if(remote.status==='completed'&&!done){state.habitLogs[`${h.id}_${today}`]=Number(h.target||1);pulled++}}catch(e){if((e as any).status!==404)throw e;h={...h,microsoftTodoId:null}}}const payload=habitPayload(h,today,logValue(state,h.id,today)>=Number(h.target||1));if(h.microsoftTodoDate===today&&h.microsoftTodoId){remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(h.microsoftTodoId)}`,{method:'PATCH',body:JSON.stringify(payload)});updated++}else{remote=await graph(tok,`/me/todo/lists/${encodeURIComponent(listId)}/tasks`,{method:'POST',body:JSON.stringify(payload)});created++}state.habits[i]={...h,microsoftTodoId:remote.id,microsoftTodoDate:today,microsoftTodoSyncedAt:new Date().toISOString()}}
 const now=new Date().toISOString();await admin('planner_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,schema_version:8,state,updated_at:now})});await admin(`microsoft_todo_connections?user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',body:JSON.stringify({last_synced_at:now,updated_at:now})});return {state,created,updated,pulled,lastSyncedAt:now}}
async function callback(req:Request){const u=new URL(req.url),code=u.searchParams.get('code')||'',state=u.searchParams.get('state')||'',err=u.searchParams.get('error_description')||u.searchParams.get('error')||'';if(err)return Response.redirect(`${APP_URL}?microsoftTodo=error&message=${encodeURIComponent(err)}`,302);const p=await verifyState(state);const t:any=await token(new URLSearchParams({client_id:MS_CLIENT_ID,client_secret:MS_CLIENT_SECRET,code,redirect_uri:REDIRECT_URI,grant_type:'authorization_code',scope:SCOPES}));if(!t.refresh_token)throw new Error('A Microsoft não retornou autorização persistente.');const me:any=await graph(t.access_token,'/me?$select=id,displayName,mail,userPrincipalName');const encrypted=await encryptToken(t.refresh_token);const now=new Date().toISOString();await admin('microsoft_todo_connections?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:p.userId,...encrypted,microsoft_account_id:me.id,microsoft_email:me.mail||me.userPrincipalName||'',granted_scopes:t.scope||SCOPES,connected_at:now,updated_at:now})});return Response.redirect(`${p.returnTo||APP_URL}?microsoftTodo=connected`,302)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});try{if(req.method==='GET')return await callback(req);if(req.method!=='POST')return json(req,{error:'Método não permitido'},405);const user=await authUser(req);if(!user?.id)return json(req,{error:'Entre no Planner para continuar.'},401);let b:any={};try{b=await req.json()}catch{};const ready=Boolean(MS_CLIENT_ID&&MS_CLIENT_SECRET&&TOKEN_KEY);if(b.action==='status'){const c=await connection(user.id);return json(req,{ok:true,ready,connected:Boolean(c),email:c?.microsoft_email||'',lastSyncedAt:c?.last_synced_at||null})}if(!ready)return json(req,{error:'A integração Microsoft ainda precisa das credenciais do aplicativo no Supabase.'},503);if(b.action==='connect'){const st=await signState({userId:user.id,returnTo:b.returnTo||APP_URL,exp:Date.now()+10*60*1000});const q=new URLSearchParams({client_id:MS_CLIENT_ID,response_type:'code',redirect_uri:REDIRECT_URI,response_mode:'query',scope:SCOPES,state:st,prompt:'select_account'});return json(req,{ok:true,url:`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${q}`})}if(b.action==='sync')return json(req,{ok:true,...await syncUser(user.id)});return json(req,{error:'Ação desconhecida'},400)}catch(e){console.error(e);return json(req,{error:e instanceof Error?e.message:'Falha na integração Microsoft'},500)}});
